<?php
declare(strict_types=1);
require_once __DIR__.'/../shared/response.php'; require_once __DIR__.'/../shared/request.php'; require_once __DIR__.'/../shared/auth.php';
methodOnly('POST'); requireAdmin();
safeApi(function():void{
 $db=apiDatabase();$i=jsonRequest();$db->beginTransaction();$stock=max(0,(int)($i['stock_quantity']??0));$threshold=max(0,(int)($i['low_stock_threshold']??5));$st=$stock<=0?'OUT_OF_STOCK':($stock<=$threshold?'LOW_STOCK':'IN_STOCK');
 $q=$db->prepare('INSERT INTO products(name,slug,sku,short_description,description,category_id,sub_category_id,selling_price,strike_price,offer_price,weight,weight_unit,ingredient_type,key_ingredients,storage_shelf_life,manage_inventory,stock_quantity,low_stock_threshold,stock_status,status,featured,is_combo_offer,show_in_hero,main_image) VALUES(:name,:slug,:sku,:short,:desc,:cat,:sub,:sell,:strike,:offer,:weight,:unit,:ingredient,:ingredients,:storage,:manage,:stock,:threshold,:stockstatus,:status,:featured,:combo,:hero,:image)');
 $q->execute([':name'=>inputString($i,'name',true),':slug'=>inputString($i,'slug',true),':sku'=>inputString($i,'sku'),':short'=>inputString($i,'short_description'),':desc'=>inputString($i,'description'),':cat'=>(int)($i['category_id']??0),':sub'=>$i['sub_category_id']??null,':sell'=>(float)($i['selling_price']??0),':strike'=>$i['strike_price']??null,':offer'=>$i['offer_price']??null,':weight'=>inputString($i,'weight'),':unit'=>inputString($i,'weight_unit'),':ingredient'=>inputString($i,'ingredient_type'),':ingredients'=>inputString($i,'key_ingredients'),':storage'=>inputString($i,'storage_shelf_life'),':manage'=>(int)($i['manage_inventory']??1),':stock'=>$stock,':threshold'=>$threshold,':stockstatus'=>$st,':status'=>strtoupper((string)($i['status']??'ACTIVE')),':featured'=>(int)($i['featured']??0),':combo'=>(int)($i['is_combo_offer']??0),':hero'=>(int)($i['show_in_hero']??0),':image'=>inputString($i,'main_image')]);
 $id=(int)$db->lastInsertId(); saveVariations($db,$id,$i['variations']??[]);$db->commit();jsonResponse(true,'Product created successfully.',['id'=>$id],[],201);
});
function saveVariations(PDO $db,int $id,array $items):void{$q=$db->prepare('INSERT INTO product_variations(product_id,variation_name,sku,weight,weight_unit,selling_price,strike_price,stock_quantity,status) VALUES(:p,:n,:sku,:w,:u,:s,:st,:q,:status)');foreach($items as $v)$q->execute([':p'=>$id,':n'=>trim((string)($v['variation_name']??'')),':sku'=>$v['sku']??null,':w'=>$v['weight']??null,':u'=>$v['weight_unit']??null,':s'=>(float)($v['selling_price']??0),':st'=>$v['strike_price']??null,':q'=>max(0,(int)($v['stock_quantity']??0)),':status'=>$v['status']??'ACTIVE']);}
