ALTER TABLE enquiries
    MODIFY COLUMN enquiry_type VARCHAR(20) NOT NULL DEFAULT 'CONTACT',
    MODIFY COLUMN company_name VARCHAR(200) NULL,
    MODIFY COLUMN email VARCHAR(255) NULL,
    MODIFY COLUMN subject VARCHAR(200) NULL,
    MODIFY COLUMN message TEXT NULL,
    MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'NEW';

UPDATE enquiries
SET enquiry_type = CASE LOWER(enquiry_type)
    WHEN 'bulk' THEN 'BULK_ORDER'
    WHEN 'bulk_order' THEN 'BULK_ORDER'
    ELSE 'CONTACT'
END;

UPDATE enquiries
SET status = CASE UPPER(status)
    WHEN 'CONTACTED' THEN 'IN_PROGRESS'
    WHEN 'CLOSED' THEN 'CLOSED'
    WHEN 'RESOLVED' THEN 'RESOLVED'
    WHEN 'IN_PROGRESS' THEN 'IN_PROGRESS'
    ELSE 'NEW'
END;

ALTER TABLE enquiries
    MODIFY COLUMN enquiry_type ENUM('CONTACT', 'BULK_ORDER') NOT NULL DEFAULT 'CONTACT',
    MODIFY COLUMN status ENUM('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL DEFAULT 'NEW',
    ADD COLUMN admin_notes TEXT NULL AFTER status;
